# Methods centered on predicting at-risk students {#predictive}

**Under construction**

Over the last twenty years, there has an increasing amount of work in the applied social sciences that explore the use of what [@breiman2001twocultures] refers to as "algorithmic modelling"", as opposed to "data modelling". He describes these as two cultures, the former being made up of mostly computer scientists, and the latter being made up statisticians (the methods therein are the ones explored in the previous chapter of this report). The key metric in such classical methods are __goodness of fit__, and such "explanatory"" modelling aims to find associative and causal relationships between predictors. Meanwhile, "algorithmic"", or "predictive"" methods emphasize determining any function that maps input variables to output responses, with less regard for a probabilistic framework that allows for causation, focusing solely on emprirical precision[@shmueli2010explain]. In the recently published **Handbok of Learning Analytics**[@hla2017], published by the Society of Learning Analytics Research, [@bergner_measurement_2017] asserts that the researchers looking into educational data stand to gain from understanding the nuances of both methodologies, as previous work has shown the strengths and weakeness of either in this domain.

The previous chapter explored how classical statistical models can be built and used to determine what are the factors that influence dropout. This is useful for policy makers and admninstrators who want to dedicate resources in the most strategic places. However this chapter will explore models whose inner workings are less interpretable, but whose primary objective is prediction/identification of at-risk students. This is useful in the context where college administration has some blanket intervention that it would like to apply, and we just want to ensure that the students most in need are reached. Despite the less clear interpratability of factors in these _predictive_ models (as compared to the _explanatory_ models in the previous chapter), we will stil explore methods to "open up the black box", and determine which features are most important in achieving both accrate and sensitive prediction.

## Decision Trees and Random Forests

## Neural Networks
